### Linear Regression


In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error
import matplotlib.pyplot as plt



In [2]:
X = np.array([[12],
            [23],
            [34],
            [45], 
            [56], 
            [67], 
            [78], 
            [89], 
            [123], 
            [134]])
Y = np.array([240, 1135, 2568, 4521, 7865, 9236, 11932, 14589, 19856, 23145])

Model = LinearRegression()
Model.fit(X,Y)

y_predict = Model.predict(X)
data_size = len(X)
print("coefficients:",Model.coef_)
print("\nIntercept:",Model.intercept_)
print("\nY_predicted:",y_predict)

SSE_1 = mean_squared_error(Y,y_predict)*data_size #mean square error give the mean of all error we just mutliply with the size to get sum of error
print("\nSSE:",SSE_1)

R_square_1 = r2_score(Y,y_predict)
print(f"R_square:{R_square_1}")



coefficients: [192.68653416]

Intercept: -3227.879907776485

Y_predicted: [ -915.64149789  1203.91037783  3323.46225356  5443.01412929
  7562.56600501  9682.11788074 11801.66975647 13921.22163219
 20472.56379353 22592.11566926]

SSE: 4200322.583387672
R_square:0.9924529470512246


### Polynomial Regression(Degree:2)

In [3]:
from sklearn.preprocessing import PolynomialFeatures


poly_feature = PolynomialFeatures(degree=2) #initializong the number of features for the model
x_2 = poly_feature.fit_transform(X) #transform the original data in the form of 2 degree[1,x,x^2] as 2d matrix
print(x_2)
model= LinearRegression()
model.fit(x_2,Y)

y2_predict = model.predict(x_2)
print(f"\ny_predict:{y2_predict}")

print(f"\nCoefficient:{model.coef_}")
print(f"\nIntercept:{model.intercept_}")
SSE_2 = mean_squared_error(Y,y2_predict)*data_size #mean square error give the mean of all error we just mutliply with the size to get sum of error
print("\nSSE:",SSE_2)

R_square_2 = r2_score(Y,y2_predict)
print(f"\nR_square:{R_square_2}")

[[1.0000e+00 1.2000e+01 1.4400e+02]
 [1.0000e+00 2.3000e+01 5.2900e+02]
 [1.0000e+00 3.4000e+01 1.1560e+03]
 [1.0000e+00 4.5000e+01 2.0250e+03]
 [1.0000e+00 5.6000e+01 3.1360e+03]
 [1.0000e+00 6.7000e+01 4.4890e+03]
 [1.0000e+00 7.8000e+01 6.0840e+03]
 [1.0000e+00 8.9000e+01 7.9210e+03]
 [1.0000e+00 1.2300e+02 1.5129e+04]
 [1.0000e+00 1.3400e+02 1.7956e+04]]

y_predict:[ -566.94987085  1362.52273001  3329.13440486  5332.8851537
  7373.77497653  9451.80387336 11566.97184417 13719.27888898
 20606.6691895  22910.90880973]

Coefficient:[0.00000000e+00 1.70035246e+02 1.53467248e-01]

Intercept:-2629.4721113594715

SSE: 3737254.390144427

R_square:0.9932849784259391


In [4]:
from sklearn.preprocessing import PolynomialFeatures


poly_feature = PolynomialFeatures(degree=3) #initializong the number of features for the model
x_3 = poly_feature.fit_transform(X) #transform the original data in the form of 2 degree[1,x,x^2] as 2d matrix
print(x_3)

model= LinearRegression()
model.fit(x_3,Y)

y3_predict = model.predict(x_3)
print(f"\ny_predict:{y3_predict}")

print(f"Coefficient:{model.coef_}")
print(f"Intercept:{model.intercept_}")

SSE_3 = mean_squared_error(Y,y3_predict)*data_size #mean square error give the mean of all error we just mutliply with the size to get sum of error
print("\nSSE:",SSE_3)

R_square_3 = r2_score(Y,y3_predict)
print(f"R_square:{R_square_3}")

[[1.000000e+00 1.200000e+01 1.440000e+02 1.728000e+03]
 [1.000000e+00 2.300000e+01 5.290000e+02 1.216700e+04]
 [1.000000e+00 3.400000e+01 1.156000e+03 3.930400e+04]
 [1.000000e+00 4.500000e+01 2.025000e+03 9.112500e+04]
 [1.000000e+00 5.600000e+01 3.136000e+03 1.756160e+05]
 [1.000000e+00 6.700000e+01 4.489000e+03 3.007630e+05]
 [1.000000e+00 7.800000e+01 6.084000e+03 4.745520e+05]
 [1.000000e+00 8.900000e+01 7.921000e+03 7.049690e+05]
 [1.000000e+00 1.230000e+02 1.512900e+04 1.860867e+06]
 [1.000000e+00 1.340000e+02 1.795600e+04 2.406104e+06]]

y_predict:[  -60.47613133  1278.67024851  2968.13897682  4937.84548286
  7117.70519591  9437.63354525 11827.54596015 14217.35786988
 20851.4921867  22511.08666525]
Coefficient:[ 0.00000000e+00  5.82086124e+01  2.05315213e+00 -8.77592922e-03]
Intercept:-1039.468580569308

SSE: 2585783.3430112065
R_square:0.9953539178440843


In [5]:
import pandas as pd
data={
    'SSE':[SSE_1, SSE_2, SSE_3],
    'R_square':[R_square_1,R_square_2,R_square_3]
}
df=pd.DataFrame(data,index=["Degree_1","Degree_2","Degree_3"])
df

SSE  R_square
Degree_1  4.200323e+06  0.992453
Degree_2  3.737254e+06  0.993285
Degree_3  2.585783e+06  0.995354