## Logistic Regression

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
data = pd.read_csv('diabetes.csv')
print("Number of items:",data.shape)
data.head()

Number of items: (768, 9)


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
# Data preparation

X = data.iloc[:,:-1].values # iloc used to select ,.value for convert to numpy
print("Independent_feature:\n",X)
print("\nShape_X:",X.shape)
Y = data.iloc[:,-1].values
print("\nDependent_feature:\n",Y)
print("\nshape_Y",Y.shape)

Independent_feature:
 [[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]

Shape_X: (768, 8)

Dependent_feature:
 [1 0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0
 1 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1
 1 0 0 1 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0
 1 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 1
 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0
 1 0 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 1 1 1 0 0
 1

In [ ]:
model = LogisticRegression()
model.fit(X,Y)
y_predict = model.predict(X)
print(y_predict)
accuracy = accuracy_score(Y,y_predict)
print(accuracy)

[1 0 1 0 1 0 0 1 1 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 0 1 0 0 0 0 1
 0 0 1 1 1 0 1 1 1 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1
 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 1 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 1 0 0 0 0 0
 1 1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 0 1 0 0 0 0 1 1
 0 1 0 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1
 1 1 1 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 1 0 0 1
 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 1 0 0 1 0 1
 0 0 1 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 1 0 1 0 0 0 0 0 0
 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0 0 1 0 0
 0 1 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1
 0 0 0 1 0 0 1 0 1 0 0 0 

/home/aadharsh/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [5]:
print(accuracy)


0.7825520833333334


## Split training data and test data into 80% and 20% 

In [6]:
x1_train, x1_test, y1_train, y1_test = train_test_split(X, Y, test_size = .2, random_state= 2) # raandom state used to control the randomness  of split in every run
print("x_train:\n",x1_train)
print("\nx_test:\n",x1_test)
print("\ny_train:\n",y1_train)
print("\ny_test:\n",y1_test)

x_train:
 [[1.000e+00 1.240e+02 7.400e+01 ... 2.780e+01 1.000e-01 3.000e+01]
 [1.000e+00 9.500e+01 8.200e+01 ... 3.500e+01 2.330e-01 4.300e+01]
 [0.000e+00 9.400e+01 7.000e+01 ... 4.350e+01 3.470e-01 2.100e+01]
 ...
 [4.000e+00 1.250e+02 7.000e+01 ... 2.890e+01 1.144e+00 4.500e+01]
 [3.000e+00 1.160e+02 7.400e+01 ... 2.630e+01 1.070e-01 2.400e+01]
 [4.000e+00 1.100e+02 6.600e+01 ... 3.190e+01 4.710e-01 2.900e+01]]

x_test:
 [[  2.     88.     74.    ...  29.      0.229  22.   ]
 [  2.    129.     84.    ...  28.      0.284  27.   ]
 [  0.    102.     78.    ...  34.5     0.238  24.   ]
 ...
 [  0.    132.     78.    ...  32.4     0.393  21.   ]
 [  5.    137.    108.    ...  48.8     0.227  37.   ]
 [  1.     73.     50.    ...  23.      0.248  21.   ]]

y_train:
 [0 1 0 1 0 1 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 0 0 1 1 0 1 0
 0 0 1 1 1 1 1 0 0 1 1 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 1 1 1 1 0 0 0 0 1 0 1
 1 0 0 0 0 0 1 0 1 1 0 1 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0


In [7]:
model1 = LogisticRegression()
model1.fit(x1_train,y1_train)
y1_predict = model1.predict(x1_test)
print(y1_predict)
accuracy1 =accuracy_score(y1_test,y1_predict)
print(accuracy1*100)


[0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1 1 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 1 1 1 0 0 1 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 1 0 1 0 0 0 0 0 1
 0 0 0 0 1 0]
76.62337662337663


/home/aadharsh/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


## Split training data and test data into 70% and 30% 

In [8]:
x2_train, x2_test, y2_train, y2_test = train_test_split(X, Y, test_size = .3, random_state= 3) # raandom state used to control the randomness  of split in every run
print("x_train:\n",x2_train)
print("\nx_test:\n",x2_test)
print("\ny_train:\n",y2_train)
print("\ny_test:\n",y2_test)

x_train:
 [[1.00e+00 1.24e+02 7.40e+01 ... 2.78e+01 1.00e-01 3.00e+01]
 [1.00e+00 1.81e+02 6.40e+01 ... 3.41e+01 3.28e-01 3.80e+01]
 [7.00e+00 1.94e+02 6.80e+01 ... 3.59e+01 7.45e-01 4.10e+01]
 ...
 [4.00e+00 9.00e+01 0.00e+00 ... 2.80e+01 6.10e-01 3.10e+01]
 [1.00e+00 1.11e+02 8.60e+01 ... 3.01e+01 1.43e-01 2.30e+01]
 [6.00e+00 1.15e+02 6.00e+01 ... 3.37e+01 2.45e-01 4.00e+01]]

x_test:
 [[  1.    101.     50.    ...  24.2     0.526  26.   ]
 [  4.    156.     75.    ...  48.3     0.238  32.   ]
 [  1.     97.     66.    ...  23.2     0.487  22.   ]
 ...
 [  8.    109.     76.    ...  27.9     0.64   31.   ]
 [  3.    170.     64.    ...  34.5     0.356  30.   ]
 [  4.    115.     72.    ...  28.9     0.376  46.   ]]

y_train:
 [0 1 1 1 1 1 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 1 0 1
 0 0 1 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0
 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 1 1 0 0 1 0 1 1 0 0
 1 1 0 0 0 0 1 1 0 0 0 1 0 0 0 1 1 1

In [9]:
model2 = LogisticRegression()
model2.fit(x2_train,y2_train)
y2_predict = model2.predict(x2_test)
print(y2_predict)
accuracy2 =accuracy_score(y2_test,y2_predict)
print(accuracy2*100)


[0 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0
 0 1 1 1 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 1 0 0 0
 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 1 1 0 0 0 1 0 1 0 0 1 0 1 0 0 0 1 0 0 0
 0 1 1 1 0 1 1 1 0 0 0 0 0 0 1 0 1 0 1 1 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1
 0 0 1 0 1 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 1
 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 0 1 1 0 1 0 1 0 0 0 1 0 0 0 0 1 0
 0 1 0 1 0 0 0 1 0]
75.32467532467533


/home/aadharsh/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


## Split training data and test data into 60% and 40% 

In [10]:
x3_train, x3_test, y3_train, y3_test = train_test_split(X, Y, test_size = .4, random_state= 4) # raandom state used to control the randomness  of split in every run
print("x_train:\n",x3_train)
print("\nx_test:\n",x3_test)
print("\ny_train:\n",y3_train)
print("\ny_test:\n",y3_test)

x_train:
 [[  5.     96.     74.    ...  33.6     0.997  43.   ]
 [  2.    106.     56.    ...  29.      0.426  22.   ]
 [  6.     93.     50.    ...  28.7     0.356  23.   ]
 ...
 [  6.    107.     88.    ...  36.8     0.727  31.   ]
 [  2.     75.     64.    ...  29.7     0.37   33.   ]
 [  2.    107.     74.    ...  33.6     0.404  23.   ]]

x_test:
 [[1.00e+00 1.00e+02 6.60e+01 ... 3.20e+01 4.44e-01 4.20e+01]
 [9.00e+00 5.70e+01 8.00e+01 ... 3.28e+01 9.60e-02 4.10e+01]
 [0.00e+00 1.00e+02 7.00e+01 ... 3.08e+01 5.97e-01 2.10e+01]
 ...
 [7.00e+00 1.14e+02 6.60e+01 ... 3.28e+01 2.58e-01 4.20e+01]
 [1.00e+00 7.10e+01 6.20e+01 ... 2.18e+01 4.16e-01 2.60e+01]
 [1.00e+00 8.40e+01 6.40e+01 ... 3.69e+01 4.71e-01 2.80e+01]]

y_train:
 [0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 0 0 0 1 0 0 1 0 0 1 0
 0 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 1 0 1 1 1 0 0 0 0
 0 0 0 0 0 0 1 1 0 1 1 1 1 1 1 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 1 1 0 0
 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 1

In [11]:
model3 = LogisticRegression()
model3.fit(x3_train,y3_train)
y3_predict = model3.predict(x3_test)
print(y3_predict)
accuracy3 =accuracy_score(y3_test,y3_predict)
print(accuracy3*100)


[0 0 0 0 0 1 1 0 1 0 1 0 0 0 0 1 1 1 0 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 1
 1 0 1 1 0 0 1 0 0 0 1 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 1 0 0 0 1 1 0 0 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1
 1 1 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 1 1 1 0
 0 0 0 0 1 1 0 0 0 0 1 1 1 0 0 0 0 0 1 0 1 0 1 1 0 0 0 1 1 1 0 0 1 0 0 1 0
 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 1 0 1
 1 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1 0
 1 0 0 1 0 1 0 0 1 0 1 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 0 1 0 0 0 1 0 0 1 0 1
 1 1 0 0 1 0 0 0 1 0 0 0]
79.54545454545455


/home/aadharsh/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [12]:
accuracy_rates ={
    'Accuracy':[accuracy1*100,accuracy2*100,accuracy3*100]   
}

frame = pd.DataFrame(accuracy_rates,index=["80_20", "70_30", "60_40"])
frame

Accuracy
80_20  76.623377
70_30  75.324675
60_40  79.545455